### PR TITLE
Add new component types & fix bugs

### PR DESCRIPTION
**Pull request by aheber**
Moved default save location to OS's temp directory
Fix bug where components nested under HTML tags weren't being processed
Added optional apex controller mapping
Added optional event mapping
Added use of meta tags to hint at dynamically created components
Beginnings of color coding

### CODE REVIEW

**Comment by aheber** [comment]
@jstvz I saw your feedback on my issue (#1) but I had already taken a run at adding the features. I realize what I came up with isn't quite what you were thinking but happy to make any changes to align. Had some time last night while I was stewing on this. I may take a pass this week at converting to the UML style, shouldn't be too bad. I think it would just mean double-entry.

I hadn't even thought of using aura:dependency and will convert to using that. Should be fairly simple to move away from my hacked meta tags.

I put some overly simple color coding in for apex and event relationships. Still a long way to go there and needs a more flexible application pattern.

**Comment by jstvz** [comment]
@aheber, I'm traveling this week, so I'll take a closer look after I get back, but this looks fine on a first pass. 

 I'm thinking MIT for license, FYI.

**Comment by aheber** [comment]
No hurry. I have it working for me which is all I need for now.

**Review by jstvz — APPROVED** [review]
Looks good, thanks @aheber

**Pull request merged**
